artifacts_root: artifacts

DataIngestion:
  root_dir: artifacts/data_ingestion
  data_source: data/disease_data.zip
  data_dir: artifacts/data_ingestion
  STATUS_FILE: artifacts/data_ingestion/status.txt

DataValidation:
  root_dir: artifacts/data_validation
  data_dir: artifacts/data_ingestion/data
  STATUS_FILE: artifacts/data_validation/status.txt  # status of data validation 

Preprocessing: 
  root_dir: artifacts/preprocessing
  data_path: artifacts/data_ingestion
  train_data_dir: artifacts/preprocesssing/data/train
  val_data_dir: artifacts/preprocesssing/data/val
  test_data_dir: artifacts/preprocesssing/data/test
  STATUS_FILE: artifacts/preprocessing/status.txt